#!/bin/bash

NODE_NUMBER=$1
ROOT_PATH=$HOME/temp

function param_check {
	if [ "$NODE_NUMBER" == "0" ] || [ "$NODE_NUMBER" == "1" ]
	then
		return 0
	else
		echo "Param cannot be empty"
		exit 0
	fi 
}

param_check && {
	# $config = /etc/opt/ft/spine
	mkdir -p $ROOT_PATH/etc/opt/ft/spine
	mkdir -p $ROOT_PATH/etc/opt/ft/spine/nodes
	# $LOGDIR = /var/opt/ft/log/webrick.log
	mkdir -p $ROOT_PATH/var/opt/ft/log
	# $SPOOL = /var/spool
	mkdir -p $ROOT_PATH/var/spool
	# /etc/sysconfig/spine
	mkdir -p $ROOT_PATH/etc/sysconfig
	# /etc/opt/ft
	mkdir -p $ROOT_PATH/etc/opt/ft
	# /var/opt/ft
	mkdir -p $ROOT_PATH/var/opt/ft
	# /var/opt/ft/spine/localnode
	mkdir -p $ROOT_PATH/var/opt/ft/spine
	# /usr/lib/spine/config
	# /usr/lib/spine/bin/dmiconfig
	mkdir -p $ROOT_PATH/usr/lib/spine/bin
	# /usr/sbin/spine
	mkdir -p $ROOT_PATH/usr/sbin
	# /sbin/pm_describe
	mkdir -p $ROOT_PATH/sbin
	# /etc/platform_management/pm.xml
	mkdir -p $ROOT_PATH/etc/platform_management

	if [ "$NODE_NUMBER" == "0" ]
	then
		cp -f $HOME/workspace/ruby-demo/spine/configs/node0-config-uuid $ROOT_PATH/etc/opt/ft/node-config-uuid
	else
		cp -f $HOME/workspace/ruby-demo/spine/configs/node1-config-uuid $ROOT_PATH/etc/opt/ft/node-config-uuid
	fi
	echo "copy node-config-uuid to $ROOT_PATH/etc/opt/ft/node-config-uuid"
	cp -f $HOME/workspace/ruby-demo/spine/dmiconfigure.rb $ROOT_PATH/usr/lib/spine/bin/dmiconfigure
	echo "copy dmiconfigure.rb to $ROOT_PATH/usr/lib/spine/bin/dmiconfigure"
    # /usr/lib/spine/configure
	cp -f $HOME/workspace/ruby-demo/spine/configure.rb $ROOT_PATH/usr/lib/spine/configure
	echo "copy configure.rb to $ROOT_PATH/usr/lib/spine/configure"
	# /usr/sbin/spine
	cp -f $HOME/workspace/ruby-demo/spine/spine.rb $ROOT_PATH/usr/sbin/spine
	echo "copy spine.rb to $ROOT_PATH/usr/sbin/spine"
	# /sbin/pm_describe
	cp -f $HOME/workspace/ruby-demo/spine/configs/pm_describe $ROOT_PATH/sbin/pm_describe
	echo "copy pm_describe to $ROOT_PATH/sbin/pm_describe"
	
	echo "Init finished"
}
