#!/usr/bin/env ruby

system_info = %x{dmidecode -t 1}

props = { }

system_info.each_line do |line|
    (key, value) = line.split(':').map {|a| a.strip}
    case key
    when 'Manufacturer'
        props[:manufacturer] = value
    when 'Product Name'
        props[:model] = value
    when 'Serial Number'
        props[:serial_number] = value
    when 'UUID'
        props[:uuid] = value
    end
end

if props[:serial_number].nil? || props[:serial_number].start_with?("...")
  system_info = %x{dmidecode -t 2}
  system_info.each_line do |line|
    (key, value) = line.split(':').map {|a| a.strip}
    case key
      when 'Serial Number'
        props[:serial_number] = value
    end
  end
end

output = "<?xml version='1.0'?>\n"
output << "<pm class='PM' id='#{props[:uuid]}'>\n"
output << "  <manufacturer type='avd:enum:Manufacturer'>\n"
output << "    <short_desc>#{props[:manufacturer]}</short_desc>\n"
output << "  </manufacturer>\n"
output << "  <model type='avd:enum:PM-Model'>\n"
output << "    <short_desc>#{props[:model]}</short_desc>\n"
output << "  </model>\n"
output << "  <serial_number type='string'>#{props[:serial_number]}</serial_number>\n"
output << "</pm>\n"

puts output

