#!/bin/bash --login

#=============================================================================

# Use example:
# ./execute_fttest_cmd {deploy folder}                       {dut name}
#                           $1                                    $2
#                /test_logs1/{username}/{workspace}              mali

#=============================================================================

# This script is used to run fttest under specified folder.

#=============================================================================

DEPLOY_DIR=$1
DUT_NAME=$2
USER_NAME=`whoami`
cd $DEPLOY_DIR
echo "run fttest under dir $DEPLOY_DIR"
FTTEST_CMD="fttest sn/null,dut=$DUT_NAME,vms=1"
if [ $# > 2 ]
then
  index=0
  for i in "$@";
  do
    if [ $index -gt 1 ]
    then
      FTTEST_CMD+=",$i"
    fi
    index=`expr $index + 1`
  done
  $($FTTEST_CMD)
else
  $($FTTEST_CMD)
fi

