#!/bin/bash

spine_pid=`ps -ef | grep -i "\[spine\]" | grep -v "grep" | awk '{print $2}' | head -1`
if [ -z "$spine_pid" ]
then
  spine_pid=""
fi
echo "find spine pid: $spine_pid"
if [ $spine_pid ]
then
  echo "send kill -9 signal to spine"
  kill -9 $spine_pid
fi
spine_new_pid=`ps -ef | grep -i "\[spine\]" | grep -v "grep" | awk '{print $2}' | head -1`
if [ -z "$spine_new_pid" ]
then
  spine_new_pid=""
fi
while [ "$spine_pid" = "$spine_new_pid" ]
do
  sleep 1
  spine_new_pid=`ps -ef | grep -i "\[spine\]" | grep -v "grep" | awk '{print $2}' | head -1`
  echo "waiting for spine to restart"
done
echo "spine restart successfully, new pid is $spine_new_pid"

