#!/usr/bin/ruby

$DUT_NAME = ARGV[0].to_s
$USER_NAME = %x{whoami}

begin
  dut = "#{$DUT_NAME }"
  user = "#{$USER_NAME}"
  dut.chomp!
  user.chomp!
  raise "dut name is required" if dut == ""
  %x{ftscp /developer/#{user}/script/common/get_everrun_passwd root@#{dut}:/root/}
  passwd = %x{ftssh root@#{dut} /root/get_everrun_passwd}
  passwd.chomp!
  %x{ftssh rm -f /root/get_everrun_passwd}
  puts "on DUT #{dut}, root password is \"#{passwd}\""
rescue Exception => e
  puts "error: #{e}"
end

