#!/bin/bash
#=============================================================================

# Use example:
# ./p2v_daily_build {workspace_path}        {dut_name}
#                             $1                 $2
#                       shanghai_build         greece

#=============================================================================

# This script is used to do the daily build for hwmonitor. It will get
# the latest modification of branch ${branch_name} under the specified 
# workspace ${workspace_path}, then switch to shanghai6 build host to
# generate the rpm by command make. Finally, it will copy the rpm to
# the specified dut ${dut_name}, and use it to replace the original.

#=============================================================================

workspace_path=$1
dut_name=$2
user_name=`whoami`
CURDIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
build_server=$(cat $CURDIR/build_server)

# All of the paramters cannot be empty string, if so, exit the script.
function check_parameters {
    echo "===================begin to check parameters========================" 
    if [ "" == "$workspace_path" ] || [ "" == "$dut_name" ]
    then
        echo "Please input the parameters!"
        exit 0
    fi
    echo "==================checked successfully========================"
}

# Generate the rpm for the latest code, and use it to replace the original
function deploy_backend_rpm {
    echo "===================begin to use the latest rpm instead of the old one========================"
    date_str=$(date "+%Y%m%d%H%M%S")
    tmp_dir="/${user_name}-tmp/${workspace_path}/p2v-${date_str}/"
    ftssh node0.$dut_name mkdir -p ${tmp_dir}
    ftssh node1.$dut_name mkdir -p ${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-third-party/virt-v2v/build/RPMS/x86_64/*.rpm root@node0.${dut_name}:${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-third-party/virt-v2v/build/RPMS/x86_64/*.rpm root@node1.${dut_name}:${tmp_dir}
    ftssh node0.$dut_name rpm -ivh --force ${tmp_dir}*.rpm
    ftssh node1.$dut_name rpm -ivh --force ${tmp_dir}*.rpm
    echo "===================replaced successfully========================"
}

# The main function for daily build
function daily_build {
    deploy_backend_rpm
}


check_parameters && daily_build
