spring:
    application:
        name: microservice-provider-user
eureka:
    instance:
        hostname: localhost
        port: 8760
        prefer-ip-address: true
    clien:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
