#!/usr/bin/ruby

require 'pathname'
require "#{File.join(Pathname.new(File.dirname(__FILE__)).realpath.parent, "lib")}/lib_prepare_workspace"

$workspace = ARGV.shift

begin
    validate($workspace)
    workspace_full_path = create_workspace_dir($workspace)
    fetch_source_code(workspace_full_path)
    add_remote(workspace_full_path)
rescue CommandError => err
    puts "#{err}"
rescue Exception => err
    "#{err} (#{err.class})\n#{err.backtrace.join("\n\tfrom ")}"
end
