#!/usr/bin/ruby

require 'pathname'
require "#{File.join(Pathname.new(File.dirname(__FILE__)).realpath.parent, "lib")}/lib_prepare_workspace"

def pre
    msg = <<EOT
./prepare_workspace workspace
EOT
    if help?(ARGV)
        puts msg
        Kernel.exit
    end
end

begin
    pre
    workspace = ARGV.shift
    validate(workspace)
    workspace_full_path = create_workspace_dir(workspace)
    fetch_source_code(workspace_full_path)
    add_remote(workspace_full_path)
    compile(workspace)
rescue SystemExit => err
rescue CommandError => err
    puts "#{err}"
rescue Exception => err
    puts "#{err} (#{err.class})\n#{err.backtrace.join("\n\tfrom ")}"
end
