#!/usr/bin/ruby

require '../lib/lib_prepare_workspace'

$workspace = ARGV.shift

begin
    validate($workspace)
    workspace_full_path = create_workspace_dir($workspace)
    fetch_source_code(workspace_full_path)
    add_remote(workspace_full_path)
    compile($workspace)
rescue CommandError => err
    puts "#{err}"
rescue Exception => err
    log.error("#{err} (#{err.class})\n#{err.backtrace.join("\n\tfrom ")}")
end
