#!/bin/bash
#=============================================================================

# Use example:
# ./checkout_branch           {repo_path}                                  {branch_name}
#                                  $1                                              $2
#                     /developer/fzhang/workspace/unity-build                  EV-3388

#=============================================================================

repo_path=$1
branch_name=$2
user_name=`whoami`
cd $repo_path
echo "===========================begin to checkout ========================"
git pull fork
git checkout $branch_name
current_branch=$(git branch | grep "* $branch_name")
echo "current branch is $current_branch"
if [ -z "$current_branch" ]
then
  echo "failed to checkout to branch $branch_name"
  exit 0
fi
git branch
echo "===========================checkout successfully========================"
