#! /bin/bash

HARNESS=${HARNESS:-7.5}
TESTDIR=$(basename $(pwd))
TESTHOST=test_logs1.sn.stratus.com
TESTROOT=/test_logs1/${USER}/everrun_build
HARNESSPATH=/test_logs/fttest2/unity-${HARNESS}/stable
if [ ! -d ${HARNESSPATH} ]; then
  echo "!!! Cannot find test harness at ${HARNESSPATH}, attempting 'current'";
  HARNESSPATH=/test_logs/fttest2/unity-${HARNESS}/current
fi
if [ ! -d ${HARNESSPATH} ]; then
  echo "!!! Cannot find test harness at ${HARNESSPATH}";
  exit 1
fi

if ! [ -d unity-stratus ]; then
  if ! [ -d unity-build ]; then
    echo "Not in an everRun workspace, EXITING..."
    exit 1
  fi
fi

if [ -d unity-stratus ]; then
  if ! [ -L unity-build ]; then
    echo "unity-build link doesn't exist, creating it and continuing"
    ln -s unity-stratus unity-build
  fi
fi

if ! [ -d unity-build/kit ]; then
  echo "There is no kit to install, EXITING"
  exit 1
fi

if ! [ -f unity-build/kit/*.kit ]; then
  echo "There is no kit file to install, EXITING"
  exit 1
fi


echo "...using test harness at ${HARNESSPATH}"



#...copy the build results over to the test domain.
mkdir -p ${TESTROOT}/${TESTDIR}
rm -rf ${TESTROOT}/${TESTDIR}/kit/*
tar --transform='flags=r;s|unity-build/||' -cf - \
  unity-build/{Components.txt,project.xml,kit} \
  --exclude=*/Packages --exclude=*/SRPMS --exclude=*/ks.cfg\
  | tar -C ${TESTROOT}/${TESTDIR} -xvf -

#...modify the kickstart file to reference the copied install kit
#...note that directory /test_logs1 is be nfsmounted from test_logs1:/vol/test_logs1
sed -e '/nfs --server/s|server=.*kit|server='${TESTHOST}' --dir='/vol${TESTROOT}/${TESTDIR}'/kit|' \
  unity-build/kit/ks.cfg > ${TESTROOT}/${TESTDIR}/kit/ks.cfg

#...extract buggrab for use by test
tar -C unity-build/unity-diagnostics -cf - buggrab \
  | tar -C ${TESTROOT}/${TESTDIR} -xvf -

#...extract avcli for use by test (deprecated)
mkdir -p ${TESTROOT}/${TESTDIR}/avcli
rpm2cpio unity-build/kit/Packages/avcli*.rpm \
  | (cd ${TESTROOT}/${TESTDIR}/avcli ; cpio -i -m -d -u )

ln -snf . ${TESTROOT}/${TESTDIR}/local
ln -snf ${HARNESSPATH} ${TESTROOT}/${TESTDIR}/project

pushd ${TESTROOT}/${TESTDIR}
fttest $@

echo "Completed at: "
date
