#!/bin/bash
#=============================================================================

# Use example:
# ./link_remote_repo           {repo_path}                                  {remote_repo}
#                                  $1                                              $2
#                     /developer/fzhang/workspace/unity-build    git@github.com:Stratus-franklinzhang/unity-stratus.git

#=============================================================================

repo_path=$1
remote_repo=$2
user_name=`whoami`
cd $repo_path
echo "===========================begin to add remote fork========================"
git remote add fork ${remote_repo}
git remote -v
echo "===========================add remote fork successfully========================"
