#!/bin/bash --login

#=============================================================================

# This script is used to submit modified scripts to betsy, do not run this
# script on betsy

#=============================================================================

function update_timestamp() {
    current_time=`date +%s`;
    echo "current time = $current_time"
    timestamp_file=$current_folder/timestamp
    if [ -f $timestamp_file ]
    then
        rm -f $timestamp_file
    fi
    echo $current_time > $timestamp_file
    chmod 444 $timestamp_file
}

current_folder=`pwd`
echo "starting coping scripts into $current_folder"
scp -r fzhang@betsy.sn.stratus.com:/developer/fzhang/script/centos* .
scp -r fzhang@betsy.sn.stratus.com:/developer/fzhang/script/common* .
update_timestamp
echo "done"
