#!/bin/bash
#=============================================================================

# Use example:
# ./p2v_daily_build {workspace_path} {branch_name} {dut_name}
#                             $1              $2           $3
#                       shanghai_build     master       greece

#=============================================================================

# This script is used to do the daily build for hwmonitor. It will get
# the latest modification of branch ${branch_name} under the specified 
# workspace ${workspace_path}, then switch to shanghai6 build host to
# generate the rpm by command make. Finally, it will copy the rpm to
# the specified dut ${dut_name}, and use it to replace the original.

#=============================================================================

workspace_path=$1
branch_name=$2
dut_name=$3
user_name=`whoami`
CURDIR=$(cd $(dirname ${BASH_SOURCE[0]}); pwd)
build_server=$(cat $CURDIR/build_server)

# All of the paramters cannot be empty string, if so, exit the script.
function check_parameters {
    echo "===================begin to check parameters========================" 
    if [ "" == "$workspace_path" ] || [ "" == "$branch_name" ] || [ "" == "$dut_name" ]
    then
        echo "Please input the parameters!"
        exit 0
    fi
    echo "==================checked successfully========================"
}

# Get the latest modification under the specified workspace
function pull_latest_code {
    echo "===================begin to pull the latest code========================"
    cd /developer/$user_name/${workspace_path}/unity-third-party/virt-v2v/
    git pull
    remote_name=$(git remote -v | grep "fork" | grep -v "grep" | awk '{print $1}' | head -1)
    if [ $remote_name ]
    then
      echo "will pull from remote $remote_name"
      git pull $remote_name
    fi    
    git checkout ${branch_name}
    current_branch=$(git branch | grep "* $branch_name")
    echo "current branch is $current_branch"
    if [ -z "$current_branch" ]
    then
      echo "failed to checkout to branch $branch_name"
      exit 0
    fi
    if [ "$current_branch" = "master" ]
    then
        git pull origin master
    else
        git pull ${remote_name} ${branch_name}
    fi
    git branch
    echo "===================pulled successfully========================"
}

# Switch to the build host, and generate rpm by make
function generate_rpm {
    echo "===================begin to generate rpm========================"
    ssh $user_name@${build_server} /developer/$user_name/script/common/generate_p2v_rpm ${workspace_path}
    echo "===================generated rpm successfully========================"
}

# Generate the rpm for the latest code, and use it to replace the original
function deploy_backend_rpm {
    echo "===================begin to use the latest rpm instead of the old one========================"
    date_str=$(date "+%Y%m%d%H%M%S")
    tmp_dir="/${user_name}-tmp/${workspace_path}/p2v-${date_str}/"
    ftssh node0.$dut_name mkdir -p ${tmp_dir}
    ftssh node1.$dut_name mkdir -p ${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-third-party/virt-v2v/build/RPMS/x86_64/*.rpm root@node0.${dut_name}:${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-third-party/virt-v2v/build/RPMS/x86_64/*.rpm root@node1.${dut_name}:${tmp_dir}
    ftssh node0.$dut_name rpm -ivh --force ${tmp_dir}*.rpm
    ftssh node1.$dut_name rpm -ivh --force ${tmp_dir}*.rpm
    echo "===================replaced successfully========================"
}

# The main function for daily build
function daily_build {
    pull_latest_code
    generate_rpm
    deploy_backend_rpm
}

check_parameters && daily_build
