#!/usr/bin/ruby

require 'fileutils'
require 'pathname'

#=============================================================================

# Use example:
# ./backend_daily_build {workspace_path} {branch_name} {dut_name} {ignore_compiling}
#                              $1              $2          $3            $4 (optional)
#                        shanghai_build      master       greece        true

#=============================================================================

# This script is used to do the daily build for SMD. It will get
# the latest modification of branch ${branch_name} under the specified 
# workspace ${workspace_path}, then switch to shanghai6 build host to
# generate the rpm by command make. Finally, it will copy the rpm to
# the specified dut ${dut_name}, and use it to replace the original.

#=============================================================================

$stdout.sync = true

def get_arg(index)
    ARGV[index].nil? ? nil : ARGV[index].chomp
end

def show_help
    msg =<<EOF
NAME
    smd_daily_build

SYNOPSIS
    smd_daily_build <workspace> <branch> <DUT>

DESCRIPTION
    This script can install everrun to a DUT, compile source code if needed

ARGUMENTS
    <workspace>         The name of workspace
    <branch>
    <DUT>               The name of DUT
    <force compile>     Whether compiling is needed (true/yes/y means compiling is needed)

EOF
    puts msg
    exit(0)
end