#!/usr/bin/expect
# This script used to check if the shanghai5 build host can be accessed, before doing the daily build
#send "use_name=`whoami`\r"
spawn ssh jsong@shanghai5.sn.stratus.com
expect eof
