#!/bin/bash
#=============================================================================

# Use example:
# ./backend_daily_build {workspace_path} {dut_name}
#                              $1              $2
#                        shanghai_build     greece

#=============================================================================

# This script is used to do the daily build for SMD and DOH. It will get
# the latest modification of branch ${branch_name} under the specified 
# workspace ${workspace_path}, then switch to shanghai6 build host to
# generate the rpm by command make. Finally, it will copy the rpm to
# the specified dut ${dut_name}, and use it to replace the original.

#=============================================================================

workspace_path=$1
dut_name=$2
user_name=`whoami`

# All of the paramters cannot be empty string, if so, exit the script.
function check_parameters {
    echo "===================begin to check parameters========================" 
    if [ "" == "$workspace_path" ] || [ "" == "$dut_name" ]
    then
        echo "Please input the parameters!"
        exit 0
    fi
    echo "==================checked successfully========================"
}

# Generate the rpm for the latest code, and use it to replace the original
function deploy_backend_rpm {
    echo "===================begin to use the latest rpm instead of the old one========================"
    date_str=$(date "+%Y%m%d%H%M%S")
    tmp_dir="/${user_name}-tmp/${workspace_path}/sm-${date_str}/"
    #ftssh $dut_name mkdir -p ${tmp_dir}
    ftssh root@node0.$dut_name mkdir -p ${tmp_dir}
    ftssh root@node1.$dut_name mkdir -p ${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-build/unity-mgmt/sm/rpm/RPMS/x86_64/sm*.rpm root@node0.${dut_name}:${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-build/unity-mgmt/sm/java/yak/rpm/RPMS/x86_64/avcli*.rpm root@node0.${dut_name}:${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-build/unity-mgmt/sm/rpm/RPMS/x86_64/sm*.rpm root@node1.${dut_name}:${tmp_dir}
    ftscp /developer/$user_name/${workspace_path}/unity-build/unity-mgmt/sm/java/yak/rpm/RPMS/x86_64/avcli*.rpm root@node1.${dut_name}:${tmp_dir}
    #ftscp /developer/$user_name/${workspace_path}/unity-build/unity-mgmt/sm/rpm/RPMS/x86_64/sm*.rpm root@${dut_name}:${tmp_dir}
    #ftscp /developer/$user_name/${workspace_path}/unity-build/unity-mgmt/sm/java/yak/rpm/RPMS/x86_64/avcli*.rpm root@${dut_name}:${tmp_dir}
    ftssh $dut_name service --status-all | grep smd
    #ftssh root@$dut_name rpm -ivh --force ${tmp_dir}sm*.rpm
    #ftssh root@$dut_name rpm -ivh --force ${tmp_dir}avcli*.rpm
    ftssh root@node0.$dut_name rpm -ivh --force ${tmp_dir}sm*.rpm
    ftssh root@node0.$dut_name rpm -ivh --force ${tmp_dir}avcli*.rpm
    ftssh root@node1.$dut_name rpm -ivh --force ${tmp_dir}sm*.rpm
    ftssh root@node1.$dut_name rpm -ivh --force ${tmp_dir}avcli*.rpm
    ftssh $dut_name service smd restart
    ftssh $dut_name service doh restart
    echo "===================replaced successfully========================"
}

# The main function for daily build
function daily_build {
    deploy_backend_rpm
}

check_parameters && daily_build
