#!/bin/bash
# ./ui_build {dut name}

DUT_NAME=$1
user_name=`whoami`
BASE_PATH=/developer/$user_name/temp
ftscp $BASE_PATH/assets.tgz root@node0.$DUT_NAME:/var/www/html/
ftscp $BASE_PATH/assets.tgz root@node1.$DUT_NAME:/var/www/html/
ASS_PATH=/var/www/html
ftssh node0.$DUT_NAME rm -rf $ASS_PATH/assets
ftssh node0.$DUT_NAME tar -xvf $ASS_PATH/assets.tgz -C $ASS_PATH/
ftssh node1.$DUT_NAME rm -rf $ASS_PATH/assets
ftssh node1.$DUT_NAME tar -xvf $ASS_PATH/assets.tgz  -C $ASS_PATH/
echo "exec finished"

