#!/bin/bash
#=============================================================================

# Use example:
# ./ui_daily_build {workspace_path} {remote_name} {branch_name} {dut_name}
#                         $1              $2            $3          $4
#                   shanghai_build   origin/fork      master        uae

#=============================================================================

# This script is used to do the daily build for UI part. It will get
# the latest modification of branch ${branch_name} under the specified 
# workspace ${workspace_path}, then switch to shanghai6 build host to
# generate the rpm by command make. Finally, it will copy the rpm to
# the specified dut ${dut_name}, and use it to replace the original.

#=============================================================================

workspace_path=$1
remote_name=$2
branch_name=$3
dut_name=$4

# All of the paramters cannot be empty string, if so, exit the script.
function check_parameters {
    echo "===================begin to check parameters========================" 
    if [ "" == "$workspace_path" ] || [ "" == "$branch_name" ] || [ "" == "$dut_name" ] || [ "" == "$remote_name" ]
    then
        echo "Please input the parameters!"
        exit 0
    fi
    echo "==================checked successfully========================"
}
 
# Check if the dut is available (the dut is reserved by jsong or is idle), if not, exit it.
function check_dut_available {
    echo "===================begin to check dut available========================"
    rinfo_message=$(rinfo | grep "^${dut_name} *[0-9]*%")
    if [ "${rinfo_message}" == "" ]
    then
         echo "The dut ${dut_name} does not exist!"
         exit 0
    elif [[ "${rinfo_message}" =~ "Reserved:" ]] && [[ "${rinfo_message}" =~ "hwu" ]]
    then
         echo "The dut is reserved by hwu"
         return 0
    fi
    echo -e "Only the dut is reserved by hwu, we can deploy the rpm to it, but the ${dut_name} is: \n${rinfo_message}"
    exit 0
}

# Verify if the shanghai6 build host can be accessed.
function verify_access {
    echo "===================begin to verify the access========================"
    /developer/jsong/script/centos7.2/access-verified
    echo "===================verified successfully========================"
}

# Get the latest modification under the specified workspace
function pull_latest_code {
    echo "===================begin to pull the latest code========================"
    cd /developer/jsong/${workspace_path}/unity-build/unity-ui
    git branch
    git fetch ${remote_name}
    git checkout -b ${branch_name} ${remote_name}/${branch_name}
    git branch
    echo "===================pulled successfully========================"
}

# Switch the shanghai6 build host, and generatem by make
function generate_rpm {
    echo "===================begin to generate rpm========================"
    ssh jsong@shanghai6.sn.stratus.com /developer/jsong/script/common/generate_ui_rpm ${workspace_path}
    echo "===================generated rpm successfully========================"
}

# Generate the rpm for the latest code, and use it to replace the original
function deploy_backend_rpm {
    echo "===================begin to use the latest rpm instead of the old one========================"
    date_str=$(date "+%Y%m%d%H%M%S")
    tmp_dir="/jsong-tmp/${workspace_path}/ui-${date_str}/"
    ftssh $dut_name mkdir -p ${tmp_dir}
    ftscp /developer/jsong/${workspace_path}/unity-build/unity-ui/rpm/RPMS/noarch/unity-ui*.rpm root@${dut_name}:${tmp_dir}
    ftssh $dut_name service --status-all | grep doh
    ftssh $dut_name rpm -i --force ${tmp_dir}unity-ui*.rpm
    ftssh $dut_name service doh restart
    echo "===================replaced successfully========================"
}

# The main function for daily build
function daily_build {
    pull_latest_code
    generate_rpm
    deploy_backend_rpm
}

check_parameters && check_dut_available && verify_access && daily_build
