#!/bin/bash
#=============================================================================

# Use example:
# ./build_stat_helper {workspace}           {branch_name}      {dut_name}
#                                  $1              $2           $3
#                              shanghai_build     master       greece

#=============================================================================

# This script is used to do the daily build for script. It will get
# the latest modification of branch ${branch_name} then copy the script to DUT
# to replace the original.

#=============================================================================

workspace_path=$1
branch_name=$2
dut_name=$3
user_name=`whoami`

# All of the paramters cannot be empty string, if so, exit the script.
function check_parameters {
    echo "===================begin to check parameters========================" 
    if [ "" == "$workspace_path" ] || [ "" == "$branch_name" ] || [ "" == "$dut_name" ]
    then
        echo "Please input the parameters!"
        exit 0
    fi
    echo "==================checked successfully========================"
}

# Get the latest modification under the specified workspace
function pull_latest_code {
    echo "===================begin to pull the latest code========================"
    cd /developer/$user_name/${workspace_path}/unity-stratus
    git pull
    remote_name=$(git remote -v | grep "fork" | grep -v "grep" | awk '{print $1}' | head -1)
    if [ $remote_name ]
    then
      echo "will pull from remote $remote_name"
      git pull $remote_name
    fi    
    git checkout ${branch_name}
    current_branch=$(git branch | grep "* $branch_name")
    echo "current branch is $current_branch"
    if [ -z "$current_branch" ]
    then
      echo "failed to checkout to branch $branch_name"
      exit 0
    fi
    if [ "$current_branch" = "master" ]
    then
        git pull origin master
    else
        git pull ${remote_name} ${branch_name}
    fi
    git branch
    echo "===================pulled successfully========================"
}

function copy_script {
    echo "===================copy script to DUT========================"
    ftscp /developer/$user_name/${workspace_path}/unity-stratus/unity-mgmt/sm/scripts/src/usr/bin/stat_helper.rb root@node0.${dut_name}:/usr/sbin/stat_helper
    ftscp /developer/$user_name/${workspace_path}/unity-stratus/unity-mgmt/sm/scripts/src/usr/bin/stat_helper.rb root@node1.${dut_name}:/usr/sbin/stat_helper
    ftscp -r /developer/$user_name/${workspace_path}/unity-stratus/unity-mgmt/sm/scripts/src/usr/bin/stat root@node0.${dut_name}:/usr/share/everrun/
    ftscp -r /developer/$user_name/${workspace_path}/unity-stratus/unity-mgmt/sm/scripts/src/usr/bin/stat root@node1.${dut_name}:/usr/share/everrun/
    ftssh root@${dut_name} systemctl restart everruninfluxdbagent
    echo "===================copy done========================"
}

# The main function for daily build
function daily_build {
    pull_latest_code
    copy_script
}

check_parameters && daily_build
