#!/usr/bin/ruby

#=============================================================================

# Use example:
# ./reserve_dut {dut_name}
#                  $1
#                greece

#=============================================================================

# This script is used to auto reserve a DUT once it is in the idle state.

#=============================================================================
$stdout.sync = true

$DUT_NAME = ARGV[0].to_s
$USER_NAME = %x{whoami}

def check_param(dut_name)
  raise "Please input the DUT name!" if dut_name.nil? || dut_name == ""
end

def reserve(dut_name, whom)
  puts "reserving... (for dut: #{dut_name})"
  pattern = Regexp.new('Reserved:[ ]([a-zA-Z]*)[ ]at')
  rinfo = %x{rinfo | grep "^#{dut_name} *[0-9]*%"}
  return if rinfo.nil?
  result = rinfo.match(pattern)
  if result
    owner = result[1]
    puts "DUT #{dut_name} is reserved by #{owner}"
    if owner == whom
      return false
    else
      return true
    end
  else
    puts "DUT #{dut_name} is reserved by nobody, will reserve it"
    %x{rschedule reserve --host=#{dut_name} --comment="overnight; testing"}
    return false
  end
end

begin
  dut_name = "#{$DUT_NAME}"
  dut_name.chomp!
  whom = "#{$USER_NAME}"
  whom.chomp!
  puts "dut name is \"#{dut_name}\", whom is \"#{whom}\""
  check_param(dut_name)
  loop {
    result = reserve(dut_name, whom)
    break unless result
    sleep 5
  }
rescue Exception => e
  puts "Exception occured during reserving => #{e}"
end

