CURRENT_DIR=$(shell pwd)
SCRIPT_LOCATION=$(CURRENT_DIR)/src/application_scanner
TEST_SCRIPT_LOCATION=$(CURRENT_DIR)/test/test_application_scanner

.PHONY: test

default: build

build:

test:
	$(TEST_SCRIPT_LOCATION) $(SCRIPT_LOCATION)
